language: python
os:
  - linux
python:
  - 3.8
services:
  - mysql
env:
  -DJANGO=1.8 DB=mysql
install:
  - pip install -r requirements.txt
before_script:
  - mysql -e 'create database test;' -u root
script:
  - python ridham/manage.py test